CREATE TABLE email_sync_state (
    mailbox_user_id VARCHAR(100) PRIMARY KEY,
    delta_link TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
