-- V15
-- Enforce, at the database level, that within one mailbox, a
-- normalized sender cannot have more than one ACTIVE task with the
-- same canonical task_fingerprint. This is the deterministic "fast
-- path" invariant for logical-task identity (exact/canonical
-- duplicates); it is not a substitute for semantic paraphrase
-- matching, which is handled in the application layer (later stage).
--
-- Scope is (source_mailbox, normalized_sender, task_fingerprint):
-- this application ingests multiple company mailboxes (see
-- EmailProcessing.mailboxUserId / Task.sourceMailbox), so two
-- different mailboxes both receiving mail from the same external
-- sender address must NOT be treated as the same logical task owner.
-- Scoping by sender alone would incorrectly merge them.
--
-- ARCHIVED tasks are deliberately excluded from the index (partial
-- index predicate: status <> 'ARCHIVED') so that an archived task's
-- identity never blocks a later, semantically-equivalent task from
-- being created — this is the core "active lifecycle" business rule.
--
-- SAFETY: adding a unique index to a table that may already violate
-- it would fail deploy with a generic Postgres error and no context.
-- Instead we explicitly check first and raise an actionable error
-- naming the remediation scripts, so this migration can never
-- "silently" corrupt data or fail without explanation.
--
-- If this migration halts here, DO NOT edit this file to bypass the
-- check. Instead:
--   1. Run db/scripts/detect_active_duplicate_tasks.sql to see the
--      offending groups.
--   2. Review and (if appropriate) run
--      db/scripts/archive_duplicate_active_tasks.sql to archive all
--      but the earliest task in each duplicate group.
--   3. Re-run the migration.

DO $$
DECLARE
    violation_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO violation_count
    FROM (
        SELECT source_mailbox, normalized_sender, task_fingerprint
        FROM tasks
        WHERE status <> 'ARCHIVED'
          AND normalized_sender IS NOT NULL
        GROUP BY source_mailbox, normalized_sender, task_fingerprint
        HAVING COUNT(*) > 1
    ) duplicate_groups;

    IF violation_count > 0 THEN
        RAISE EXCEPTION
            'V15 blocked: % (source_mailbox, normalized_sender, task_fingerprint) group(s) have more than one ACTIVE task. '
            'Run db/scripts/detect_active_duplicate_tasks.sql to inspect them, review and run '
            'db/scripts/archive_duplicate_active_tasks.sql to remediate (archives all but the earliest task '
            'per group), then re-run this migration. See migration file comments for details.',
            violation_count;
    END IF;
END $$;

CREATE UNIQUE INDEX ux_tasks_active_mailbox_sender_fingerprint
    ON tasks (source_mailbox, normalized_sender, task_fingerprint)
    WHERE status <> 'ARCHIVED' AND normalized_sender IS NOT NULL;
