package com.poc.aiassistant.service;

import java.time.Instant;
import java.util.List;

import org.junit.jupiter.api.AfterEach;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.Test;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.oauth2.client.OAuth2AuthorizedClient;
import org.springframework.security.oauth2.client.OAuth2AuthorizedClientManager;
import org.springframework.security.oauth2.core.OAuth2AccessToken;
import org.springframework.test.web.client.MockRestServiceServer;
import static org.springframework.test.web.client.match.MockRestRequestMatchers.method;
import static org.springframework.test.web.client.match.MockRestRequestMatchers.requestTo;
import static org.springframework.test.web.client.response.MockRestResponseCreators.withSuccess;
import org.springframework.web.client.RestClient;

import com.poc.aiassistant.dto.EmailDto;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

class GraphEmailServiceDashboardTest {

    @AfterEach
    void clearSecurityContext() {
        SecurityContextHolder.clearContext();
    }

    @Test
    void dashboardEmailsUsePersistedBoundaryAndFollowGraphPagination() {
        Instant boundary =
                Instant.parse("2026-09-11T09:46:10Z");

        ApplicationRuntime runtime =
                mock(ApplicationRuntime.class);

        when(runtime.startedAt())
                .thenReturn(boundary);

        OAuth2AuthorizedClientManager manager =
                mock(OAuth2AuthorizedClientManager.class);

        OAuth2AuthorizedClient client =
                mock(OAuth2AuthorizedClient.class);

        OAuth2AccessToken token =
                new OAuth2AccessToken(
                        OAuth2AccessToken.TokenType.BEARER,
                        "access-token",
                        Instant.parse("2026-09-11T09:00:00Z"),
                        Instant.parse("2026-09-11T17:00:00Z")
                );

        when(manager.authorize(any()))
                .thenReturn(client);

        when(client.getAccessToken())
                .thenReturn(token);

        Authentication authentication =
                mock(Authentication.class);

        when(authentication.isAuthenticated())
                .thenReturn(true);

        SecurityContextHolder
                .getContext()
                .setAuthentication(authentication);

        HttpServletRequest request =
                mock(HttpServletRequest.class);

        HttpServletResponse response =
                mock(HttpServletResponse.class);

        RestClient.Builder graphClientBuilder =
                RestClient.builder()
                        .baseUrl("http://graph.test");

        MockRestServiceServer server =
                MockRestServiceServer
                        .bindTo(graphClientBuilder)
                        .build();

        RestClient graphClient =
                graphClientBuilder.build();

        GraphEmailService service =
                new GraphEmailService(
                        graphClient,
                        manager,
                        runtime,
                        request,
                        response
                );

        /*
         * Resolve the connected mailbox.
         */
        server.expect(
                requestTo(
                        "http://graph.test/me?$select=id,displayName,userPrincipalName,mail"
                )
        )
        .andExpect(method(HttpMethod.GET))
        .andRespond(
                withSuccess(
                        """
                        {
                          "id": "user-1",
                          "displayName": "Merchant 1",
                          "mail": "merchant1@example.com"
                        }
                        """,
                        MediaType.APPLICATION_JSON
                )
        );

        /*
         * First Graph page.
         *
         * Match the exact URI generated by GraphEmailService,
         * including URL-encoded spaces.
         */
        server.expect(
                requestTo(
                        "http://graph.test/me/mailFolders/inbox/messages"
                                + "?$top=50"
                                + "&$orderby=receivedDateTime%20desc"
                                + "&$filter=receivedDateTime%20gt%202026-09-11T09:46:10Z"
                                + "&$select=id,subject,from,toRecipients,receivedDateTime,body"
                )
        )
        .andExpect(method(HttpMethod.GET))
        .andRespond(
                withSuccess(
                        """
                        {
                          "@odata.nextLink":
                            "http://graph.test/me/mailFolders/inbox/messages?$skiptoken=page2",

                          "value": [

                            {
                              "id": "old",
                              "subject": "Old",
                              "receivedDateTime": "2026-09-11T09:46:09Z",

                              "from": {
                                "emailAddress": {
                                  "name": "Old Sender",
                                  "address": "old@example.com"
                                }
                              },

                              "toRecipients": [],

                              "body": {
                                "content": "old"
                              }
                            },

                            {
                              "id": "exact",
                              "subject": "Exact Boundary",
                              "receivedDateTime": "2026-09-11T09:46:10Z",

                              "from": {
                                "emailAddress": {
                                  "name": "Exact Sender",
                                  "address": "exact@example.com"
                                }
                              },

                              "toRecipients": [],

                              "body": {
                                "content": "exact"
                              }
                            },

                            {
                              "id": "bad-date",
                              "subject": "Bad Date",
                              "receivedDateTime": "not-a-date",

                              "from": {
                                "emailAddress": {
                                  "name": "Bad Sender",
                                  "address": "bad@example.com"
                                }
                              },

                              "toRecipients": [],

                              "body": {
                                "content": "bad"
                              }
                            }
                          ]
                        }
                        """,
                        MediaType.APPLICATION_JSON
                )
        );

        /*
         * Second Graph page.
         */
        server.expect(
                requestTo(
                        "http://graph.test/me/mailFolders/inbox/messages?$skiptoken=page2"
                )
        )
        .andExpect(method(HttpMethod.GET))
        .andRespond(
                withSuccess(
                        """
                        {
                          "value": [

                            {
                              "id": "new",
                              "subject": "New Email",
                              "receivedDateTime": "2026-09-11T09:50:00Z",

                              "from": {
                                "emailAddress": {
                                  "name": "New Sender",
                                  "address": "new@example.com"
                                }
                              },

                              "toRecipients": [],

                              "body": {
                                "content": "new"
                              }
                            }
                          ]
                        }
                        """,
                        MediaType.APPLICATION_JSON
                )
        );

        List<EmailDto> result =
                service.getDashboardInboxEmails();

        /*
         * The boundary is strict:
         *
         * 09:46:09 -> excluded
         * 09:46:10 -> excluded
         * malformed -> excluded
         * 09:50:00 -> included
         */
        assertEquals(
                List.of("new"),
                result.stream()
                        .map(EmailDto::id)
                        .toList()
        );

        assertTrue(
                Instant.parse(
                        result.get(0).receivedDateTime()
                ).isAfter(boundary)
        );

        server.verify();
    }
}